set.biosoftwares.db(sprintf('%s/.BioInstaller', tempdir()))
install.nongithub('gmap', download.dir = sprintf('%s/gmap', tempdir()), verbose = T)
install.nongithub('gmap', download.dir = sprintf('%s/gmapsource', tempdir()), download.only = T, verbose = T)
install.bioinfo('samtools', download.dir = sprintf('%s/testbio/samtools', tempdir()), name.saved = "samtools",verbose = T)

#install.bioinfo('annovar', download.dir = sprintf('%s/testbio/annovar', tempdir()), name.saved = "annovar_latest", verbose = T, download.only = T)
#install.bioinfo('annovar', download.dir = sprintf('%s/testbio/annovar', tempdir()), name.saved = "annovar_latest", decompress = F)
#install.bioinfo('annovar', download.dir = sprintf('%s/testbio/annovar', tempdir()), name.saved = "annovar_latest")
#install.bioinfo('edena', download.dir = sprintf('%s/edena', tempdir()), name.saved = "edena_latest")
#print(get.info("annovar_latest"))
#print(list.files(sprintf('%s/testbio/annovar', tempdir())))
