workdir <- tempdir()
dir.create(sprintf("%s/tmp/", workdir))
dir.create(sprintf("%s/tmp1/", workdir))
test.file <- sprintf("%s/tmp1/test", workdir)
file.create(test.file)
gzip(test.file)
flog.info("Debug:extract.file()")
print(extract.file(sprintf("%s.gz", test.file), paste0(workdir, "/tmp")))
print(list.files(paste0(workdir, "/tmp")))
flog.info("Debug:install.bioinfo(show,all.names = T)")
print(install.bioinfo(show.all.names = T))
